### ISSUE TITLE
Scan is not working for swing option.

### ISSUE THREAD

**Issue by Angshumank** [pkjmesra/nseta#9]
I installed on ubuntu 20.04.4 LTS (64 bit). I tried to install using both pip and  compiling from scratch. However, most of the functionalities are not working. For example, I tried to run the command
`nseta scan -s`
and it always gives the following output

> 1/1. Fetching for []                                                                                                 
> As of 2022-05-09 14:36:39.622486+05:30, nothing to show here.

> As of 2022-05-09 14:36:39.622522+05:30, no signals to show here.
> Done.                                                                                                                  
> This run of Swing scan took 0.7 sec

Same for
 `nseta scan -i -t bband`
and
`nseta scan -l`

**Comment by Angshumank** [comment]
More informatiion, if it helps
live-quote is working. news is returning only one row.
`nseta scan-trading-strategy -S TATAMOTORS -s 2020-01-01 -e 2022-05-08 --strategy rsi`
output

> Done.                                                                                                                         
> This run of trading strategy scan took 0.2 sec
> 
> Empty DataFrame
> Columns: [Symbol, RSI-PnL, MACD-PnL, BBANDS-PnL, Reco-RSI, Reco-MACD, Reco-BBANDS]
> Index: []
>

**Comment by pkjmesra** [comment]
@Angshumank 
[THIS CODE REPO IS NO LONGER BEING MAINTAINED]

**Please use https://github.com/pkjmesra/PKScreener instead **
